# Generated by Django 3.2.7 on 2024-09-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='unknown', max_length=10)),
                ('profile_image', models.ImageField(default='images/profile_image.png', upload_to='')),
            ],
        ),
    ]
